dist: trusty

sudo: required

git:
  depth: 1

language: node_js

node_js:
- "lts/*"

before_install:
  - npm install -g npm@latest
  - cd client

install:
  - npm install

script:
  - npm run test

cache:
  directories:
    - 'node_modules'